// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"
	"database/sql"
	"fmt"
)

type DBTX interface {
	ExecContext(context.Context, string, ...any) (sql.Result, error)
	PrepareContext(context.Context, string) (*sql.Stmt, error)
	QueryContext(context.Context, string, ...any) (*sql.Rows, error)
	QueryRowContext(context.Context, string, ...any) *sql.Row
}

func New(db DBTX) *Queries {
	return &Queries{db: db}
}

func Prepare(ctx context.Context, db DBTX) (*Queries, error) {
	q := Queries{db: db}
	var err error
	if q.createFileStmt, err = db.PrepareContext(ctx, createFile); err != nil {
		return nil, fmt.Errorf("error preparing query CreateFile: %w", err)
	}
	if q.createMessageStmt, err = db.PrepareContext(ctx, createMessage); err != nil {
		return nil, fmt.Errorf("error preparing query CreateMessage: %w", err)
	}
	if q.createSessionStmt, err = db.PrepareContext(ctx, createSession); err != nil {
		return nil, fmt.Errorf("error preparing query CreateSession: %w", err)
	}
	if q.deleteFileStmt, err = db.PrepareContext(ctx, deleteFile); err != nil {
		return nil, fmt.Errorf("error preparing query DeleteFile: %w", err)
	}
	if q.deleteMessageStmt, err = db.PrepareContext(ctx, deleteMessage); err != nil {
		return nil, fmt.Errorf("error preparing query DeleteMessage: %w", err)
	}
	if q.deleteSessionStmt, err = db.PrepareContext(ctx, deleteSession); err != nil {
		return nil, fmt.Errorf("error preparing query DeleteSession: %w", err)
	}
	if q.deleteSessionFilesStmt, err = db.PrepareContext(ctx, deleteSessionFiles); err != nil {
		return nil, fmt.Errorf("error preparing query DeleteSessionFiles: %w", err)
	}
	if q.deleteSessionMessagesStmt, err = db.PrepareContext(ctx, deleteSessionMessages); err != nil {
		return nil, fmt.Errorf("error preparing query DeleteSessionMessages: %w", err)
	}
	if q.getAverageResponseTimeStmt, err = db.PrepareContext(ctx, getAverageResponseTime); err != nil {
		return nil, fmt.Errorf("error preparing query GetAverageResponseTime: %w", err)
	}
	if q.getFileStmt, err = db.PrepareContext(ctx, getFile); err != nil {
		return nil, fmt.Errorf("error preparing query GetFile: %w", err)
	}
	if q.getFileByPathAndSessionStmt, err = db.PrepareContext(ctx, getFileByPathAndSession); err != nil {
		return nil, fmt.Errorf("error preparing query GetFileByPathAndSession: %w", err)
	}
	if q.getFileReadStmt, err = db.PrepareContext(ctx, getFileRead); err != nil {
		return nil, fmt.Errorf("error preparing query GetFileRead: %w", err)
	}
	if q.getHourDayHeatmapStmt, err = db.PrepareContext(ctx, getHourDayHeatmap); err != nil {
		return nil, fmt.Errorf("error preparing query GetHourDayHeatmap: %w", err)
	}
	if q.getLastSessionStmt, err = db.PrepareContext(ctx, getLastSession); err != nil {
		return nil, fmt.Errorf("error preparing query GetLastSession: %w", err)
	}
	if q.getMessageStmt, err = db.PrepareContext(ctx, getMessage); err != nil {
		return nil, fmt.Errorf("error preparing query GetMessage: %w", err)
	}
	if q.getRecentActivityStmt, err = db.PrepareContext(ctx, getRecentActivity); err != nil {
		return nil, fmt.Errorf("error preparing query GetRecentActivity: %w", err)
	}
	if q.getSessionByIDStmt, err = db.PrepareContext(ctx, getSessionByID); err != nil {
		return nil, fmt.Errorf("error preparing query GetSessionByID: %w", err)
	}
	if q.getToolUsageStmt, err = db.PrepareContext(ctx, getToolUsage); err != nil {
		return nil, fmt.Errorf("error preparing query GetToolUsage: %w", err)
	}
	if q.getTotalStatsStmt, err = db.PrepareContext(ctx, getTotalStats); err != nil {
		return nil, fmt.Errorf("error preparing query GetTotalStats: %w", err)
	}
	if q.getUsageByDayStmt, err = db.PrepareContext(ctx, getUsageByDay); err != nil {
		return nil, fmt.Errorf("error preparing query GetUsageByDay: %w", err)
	}
	if q.getUsageByDayOfWeekStmt, err = db.PrepareContext(ctx, getUsageByDayOfWeek); err != nil {
		return nil, fmt.Errorf("error preparing query GetUsageByDayOfWeek: %w", err)
	}
	if q.getUsageByHourStmt, err = db.PrepareContext(ctx, getUsageByHour); err != nil {
		return nil, fmt.Errorf("error preparing query GetUsageByHour: %w", err)
	}
	if q.getUsageByModelStmt, err = db.PrepareContext(ctx, getUsageByModel); err != nil {
		return nil, fmt.Errorf("error preparing query GetUsageByModel: %w", err)
	}
	if q.listAllUserMessagesStmt, err = db.PrepareContext(ctx, listAllUserMessages); err != nil {
		return nil, fmt.Errorf("error preparing query ListAllUserMessages: %w", err)
	}
	if q.listFilesByPathStmt, err = db.PrepareContext(ctx, listFilesByPath); err != nil {
		return nil, fmt.Errorf("error preparing query ListFilesByPath: %w", err)
	}
	if q.listFilesBySessionStmt, err = db.PrepareContext(ctx, listFilesBySession); err != nil {
		return nil, fmt.Errorf("error preparing query ListFilesBySession: %w", err)
	}
	if q.listLatestSessionFilesStmt, err = db.PrepareContext(ctx, listLatestSessionFiles); err != nil {
		return nil, fmt.Errorf("error preparing query ListLatestSessionFiles: %w", err)
	}
	if q.listMessagesBySessionStmt, err = db.PrepareContext(ctx, listMessagesBySession); err != nil {
		return nil, fmt.Errorf("error preparing query ListMessagesBySession: %w", err)
	}
	if q.listNewFilesStmt, err = db.PrepareContext(ctx, listNewFiles); err != nil {
		return nil, fmt.Errorf("error preparing query ListNewFiles: %w", err)
	}
	if q.listSessionReadFilesStmt, err = db.PrepareContext(ctx, listSessionReadFiles); err != nil {
		return nil, fmt.Errorf("error preparing query ListSessionReadFiles: %w", err)
	}
	if q.listSessionsStmt, err = db.PrepareContext(ctx, listSessions); err != nil {
		return nil, fmt.Errorf("error preparing query ListSessions: %w", err)
	}
	if q.listUserMessagesBySessionStmt, err = db.PrepareContext(ctx, listUserMessagesBySession); err != nil {
		return nil, fmt.Errorf("error preparing query ListUserMessagesBySession: %w", err)
	}
	if q.recordFileReadStmt, err = db.PrepareContext(ctx, recordFileRead); err != nil {
		return nil, fmt.Errorf("error preparing query RecordFileRead: %w", err)
	}
	if q.renameSessionStmt, err = db.PrepareContext(ctx, renameSession); err != nil {
		return nil, fmt.Errorf("error preparing query RenameSession: %w", err)
	}
	if q.updateMessageStmt, err = db.PrepareContext(ctx, updateMessage); err != nil {
		return nil, fmt.Errorf("error preparing query UpdateMessage: %w", err)
	}
	if q.updateSessionStmt, err = db.PrepareContext(ctx, updateSession); err != nil {
		return nil, fmt.Errorf("error preparing query UpdateSession: %w", err)
	}
	if q.updateSessionTitleAndUsageStmt, err = db.PrepareContext(ctx, updateSessionTitleAndUsage); err != nil {
		return nil, fmt.Errorf("error preparing query UpdateSessionTitleAndUsage: %w", err)
	}
	if q.archiveTeamStmt, err = db.PrepareContext(ctx, archiveTeam); err != nil {
		return nil, fmt.Errorf("error preparing query ArchiveTeam: %w", err)
	}
	if q.claimNextTaskStmt, err = db.PrepareContext(ctx, claimNextTask); err != nil {
		return nil, fmt.Errorf("error preparing query ClaimNextTask: %w", err)
	}
	if q.findStaleRunsStmt, err = db.PrepareContext(ctx, findStaleRuns); err != nil {
		return nil, fmt.Errorf("error preparing query FindStaleRuns: %w", err)
	}
	if q.finishRunStmt, err = db.PrepareContext(ctx, finishRun); err != nil {
		return nil, fmt.Errorf("error preparing query FinishRun: %w", err)
	}
	if q.getTeamStmt, err = db.PrepareContext(ctx, getTeam); err != nil {
		return nil, fmt.Errorf("error preparing query GetTeam: %w", err)
	}
	if q.insertEventStmt, err = db.PrepareContext(ctx, insertEvent); err != nil {
		return nil, fmt.Errorf("error preparing query InsertEvent: %w", err)
	}
	if q.insertTeamStmt, err = db.PrepareContext(ctx, insertTeam); err != nil {
		return nil, fmt.Errorf("error preparing query InsertTeam: %w", err)
	}
	if q.listEventsAfterStmt, err = db.PrepareContext(ctx, listEventsAfter); err != nil {
		return nil, fmt.Errorf("error preparing query ListEventsAfter: %w", err)
	}
	if q.listTeamsStmt, err = db.PrepareContext(ctx, listTeams); err != nil {
		return nil, fmt.Errorf("error preparing query ListTeams: %w", err)
	}
	if q.markRunTerminalStmt, err = db.PrepareContext(ctx, markRunTerminal); err != nil {
		return nil, fmt.Errorf("error preparing query MarkRunTerminal: %w", err)
	}
	if q.nextEventSeqStmt, err = db.PrepareContext(ctx, nextEventSeq); err != nil {
		return nil, fmt.Errorf("error preparing query NextEventSeq: %w", err)
	}
	if q.updateRunHeartbeatStmt, err = db.PrepareContext(ctx, updateRunHeartbeat); err != nil {
		return nil, fmt.Errorf("error preparing query UpdateRunHeartbeat: %w", err)
	}
	if q.updateTaskCASStmt, err = db.PrepareContext(ctx, updateTaskCAS); err != nil {
		return nil, fmt.Errorf("error preparing query UpdateTaskCAS: %w", err)
	}
	if q.insertMemberStmt, err = db.PrepareContext(ctx, insertMember); err != nil {
		return nil, fmt.Errorf("error preparing query InsertMember: %w", err)
	}
	if q.getMemberStmt, err = db.PrepareContext(ctx, getMember); err != nil {
		return nil, fmt.Errorf("error preparing query GetMember: %w", err)
	}
	if q.listMembersStmt, err = db.PrepareContext(ctx, listMembers); err != nil {
		return nil, fmt.Errorf("error preparing query ListMembers: %w", err)
	}
	if q.updateMemberCASStmt, err = db.PrepareContext(ctx, updateMemberCAS); err != nil {
		return nil, fmt.Errorf("error preparing query UpdateMemberCAS: %w", err)
	}
	if q.insertTaskStmt, err = db.PrepareContext(ctx, insertTask); err != nil {
		return nil, fmt.Errorf("error preparing query InsertTask: %w", err)
	}
	if q.getTaskStmt, err = db.PrepareContext(ctx, getTask); err != nil {
		return nil, fmt.Errorf("error preparing query GetTask: %w", err)
	}
	if q.listTasksStmt, err = db.PrepareContext(ctx, listTasks); err != nil {
		return nil, fmt.Errorf("error preparing query ListTasks: %w", err)
	}
	if q.insertRunStmt, err = db.PrepareContext(ctx, insertRun); err != nil {
		return nil, fmt.Errorf("error preparing query InsertRun: %w", err)
	}
	if q.getRunStmt, err = db.PrepareContext(ctx, getRun); err != nil {
		return nil, fmt.Errorf("error preparing query GetRun: %w", err)
	}
	if q.insertAuditStmt, err = db.PrepareContext(ctx, insertAudit); err != nil {
		return nil, fmt.Errorf("error preparing query InsertAudit: %w", err)
	}
	if q.listAuditStmt, err = db.PrepareContext(ctx, listAudit); err != nil {
		return nil, fmt.Errorf("error preparing query ListAudit: %w", err)
	}
	if q.insertMessageStmt, err = db.PrepareContext(ctx, insertMessage); err != nil {
		return nil, fmt.Errorf("error preparing query InsertMessage: %w", err)
	}
	if q.getUnreadMessagesStmt, err = db.PrepareContext(ctx, getUnreadMessages); err != nil {
		return nil, fmt.Errorf("error preparing query GetUnreadMessages: %w", err)
	}
	if q.insertReceiptStmt, err = db.PrepareContext(ctx, insertReceipt); err != nil {
		return nil, fmt.Errorf("error preparing query InsertReceipt: %w", err)
	}
	if q.markDeliveredStmt, err = db.PrepareContext(ctx, markDelivered); err != nil {
		return nil, fmt.Errorf("error preparing query MarkDelivered: %w", err)
	}
	if q.markReadStmt, err = db.PrepareContext(ctx, markRead); err != nil {
		return nil, fmt.Errorf("error preparing query MarkRead: %w", err)
	}
	if q.addDependencyStmt, err = db.PrepareContext(ctx, addDependency); err != nil {
		return nil, fmt.Errorf("error preparing query AddDependency: %w", err)
	}
	if q.removeDependencyStmt, err = db.PrepareContext(ctx, removeDependency); err != nil {
		return nil, fmt.Errorf("error preparing query RemoveDependency: %w", err)
	}
	if q.getDependenciesStmt, err = db.PrepareContext(ctx, getDependencies); err != nil {
		return nil, fmt.Errorf("error preparing query GetDependencies: %w", err)
	}
	if q.getDependentsStmt, err = db.PrepareContext(ctx, getDependents); err != nil {
		return nil, fmt.Errorf("error preparing query GetDependents: %w", err)
	}
	if q.getTeamDependenciesStmt, err = db.PrepareContext(ctx, getTeamDependencies); err != nil {
		return nil, fmt.Errorf("error preparing query GetTeamDependencies: %w", err)
	}
	return &q, nil
}

func (q *Queries) Close() error {
	var err error
	if q.createFileStmt != nil {
		if cerr := q.createFileStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing createFileStmt: %w", cerr)
		}
	}
	if q.createMessageStmt != nil {
		if cerr := q.createMessageStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing createMessageStmt: %w", cerr)
		}
	}
	if q.createSessionStmt != nil {
		if cerr := q.createSessionStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing createSessionStmt: %w", cerr)
		}
	}
	if q.deleteFileStmt != nil {
		if cerr := q.deleteFileStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing deleteFileStmt: %w", cerr)
		}
	}
	if q.deleteMessageStmt != nil {
		if cerr := q.deleteMessageStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing deleteMessageStmt: %w", cerr)
		}
	}
	if q.deleteSessionStmt != nil {
		if cerr := q.deleteSessionStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing deleteSessionStmt: %w", cerr)
		}
	}
	if q.deleteSessionFilesStmt != nil {
		if cerr := q.deleteSessionFilesStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing deleteSessionFilesStmt: %w", cerr)
		}
	}
	if q.deleteSessionMessagesStmt != nil {
		if cerr := q.deleteSessionMessagesStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing deleteSessionMessagesStmt: %w", cerr)
		}
	}
	if q.getAverageResponseTimeStmt != nil {
		if cerr := q.getAverageResponseTimeStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getAverageResponseTimeStmt: %w", cerr)
		}
	}
	if q.getFileStmt != nil {
		if cerr := q.getFileStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getFileStmt: %w", cerr)
		}
	}
	if q.getFileByPathAndSessionStmt != nil {
		if cerr := q.getFileByPathAndSessionStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getFileByPathAndSessionStmt: %w", cerr)
		}
	}
	if q.getFileReadStmt != nil {
		if cerr := q.getFileReadStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getFileReadStmt: %w", cerr)
		}
	}
	if q.getHourDayHeatmapStmt != nil {
		if cerr := q.getHourDayHeatmapStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getHourDayHeatmapStmt: %w", cerr)
		}
	}
	if q.getLastSessionStmt != nil {
		if cerr := q.getLastSessionStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getLastSessionStmt: %w", cerr)
		}
	}
	if q.getMessageStmt != nil {
		if cerr := q.getMessageStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getMessageStmt: %w", cerr)
		}
	}
	if q.getRecentActivityStmt != nil {
		if cerr := q.getRecentActivityStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getRecentActivityStmt: %w", cerr)
		}
	}
	if q.getSessionByIDStmt != nil {
		if cerr := q.getSessionByIDStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getSessionByIDStmt: %w", cerr)
		}
	}
	if q.getToolUsageStmt != nil {
		if cerr := q.getToolUsageStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getToolUsageStmt: %w", cerr)
		}
	}
	if q.getTotalStatsStmt != nil {
		if cerr := q.getTotalStatsStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getTotalStatsStmt: %w", cerr)
		}
	}
	if q.getUsageByDayStmt != nil {
		if cerr := q.getUsageByDayStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getUsageByDayStmt: %w", cerr)
		}
	}
	if q.getUsageByDayOfWeekStmt != nil {
		if cerr := q.getUsageByDayOfWeekStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getUsageByDayOfWeekStmt: %w", cerr)
		}
	}
	if q.getUsageByHourStmt != nil {
		if cerr := q.getUsageByHourStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getUsageByHourStmt: %w", cerr)
		}
	}
	if q.getUsageByModelStmt != nil {
		if cerr := q.getUsageByModelStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getUsageByModelStmt: %w", cerr)
		}
	}
	if q.listAllUserMessagesStmt != nil {
		if cerr := q.listAllUserMessagesStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listAllUserMessagesStmt: %w", cerr)
		}
	}
	if q.listFilesByPathStmt != nil {
		if cerr := q.listFilesByPathStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listFilesByPathStmt: %w", cerr)
		}
	}
	if q.listFilesBySessionStmt != nil {
		if cerr := q.listFilesBySessionStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listFilesBySessionStmt: %w", cerr)
		}
	}
	if q.listLatestSessionFilesStmt != nil {
		if cerr := q.listLatestSessionFilesStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listLatestSessionFilesStmt: %w", cerr)
		}
	}
	if q.listMessagesBySessionStmt != nil {
		if cerr := q.listMessagesBySessionStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listMessagesBySessionStmt: %w", cerr)
		}
	}
	if q.listNewFilesStmt != nil {
		if cerr := q.listNewFilesStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listNewFilesStmt: %w", cerr)
		}
	}
	if q.listSessionReadFilesStmt != nil {
		if cerr := q.listSessionReadFilesStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listSessionReadFilesStmt: %w", cerr)
		}
	}
	if q.listSessionsStmt != nil {
		if cerr := q.listSessionsStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listSessionsStmt: %w", cerr)
		}
	}
	if q.listUserMessagesBySessionStmt != nil {
		if cerr := q.listUserMessagesBySessionStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listUserMessagesBySessionStmt: %w", cerr)
		}
	}
	if q.recordFileReadStmt != nil {
		if cerr := q.recordFileReadStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing recordFileReadStmt: %w", cerr)
		}
	}
	if q.renameSessionStmt != nil {
		if cerr := q.renameSessionStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing renameSessionStmt: %w", cerr)
		}
	}
	if q.updateMessageStmt != nil {
		if cerr := q.updateMessageStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing updateMessageStmt: %w", cerr)
		}
	}
	if q.updateSessionStmt != nil {
		if cerr := q.updateSessionStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing updateSessionStmt: %w", cerr)
		}
	}
	if q.updateSessionTitleAndUsageStmt != nil {
		if cerr := q.updateSessionTitleAndUsageStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing updateSessionTitleAndUsageStmt: %w", cerr)
		}
	}
	if q.archiveTeamStmt != nil {
		if cerr := q.archiveTeamStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing archiveTeamStmt: %w", cerr)
		}
	}
	if q.claimNextTaskStmt != nil {
		if cerr := q.claimNextTaskStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing claimNextTaskStmt: %w", cerr)
		}
	}
	if q.findStaleRunsStmt != nil {
		if cerr := q.findStaleRunsStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing findStaleRunsStmt: %w", cerr)
		}
	}
	if q.finishRunStmt != nil {
		if cerr := q.finishRunStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing finishRunStmt: %w", cerr)
		}
	}
	if q.getTeamStmt != nil {
		if cerr := q.getTeamStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getTeamStmt: %w", cerr)
		}
	}
	if q.insertEventStmt != nil {
		if cerr := q.insertEventStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing insertEventStmt: %w", cerr)
		}
	}
	if q.insertTeamStmt != nil {
		if cerr := q.insertTeamStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing insertTeamStmt: %w", cerr)
		}
	}
	if q.listEventsAfterStmt != nil {
		if cerr := q.listEventsAfterStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listEventsAfterStmt: %w", cerr)
		}
	}
	if q.listTeamsStmt != nil {
		if cerr := q.listTeamsStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listTeamsStmt: %w", cerr)
		}
	}
	if q.markRunTerminalStmt != nil {
		if cerr := q.markRunTerminalStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing markRunTerminalStmt: %w", cerr)
		}
	}
	if q.nextEventSeqStmt != nil {
		if cerr := q.nextEventSeqStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing nextEventSeqStmt: %w", cerr)
		}
	}
	if q.updateRunHeartbeatStmt != nil {
		if cerr := q.updateRunHeartbeatStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing updateRunHeartbeatStmt: %w", cerr)
		}
	}
	if q.updateTaskCASStmt != nil {
		if cerr := q.updateTaskCASStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing updateTaskCASStmt: %w", cerr)
		}
	}
	if q.insertMemberStmt != nil {
		if cerr := q.insertMemberStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing insertMemberStmt: %w", cerr)
		}
	}
	if q.getMemberStmt != nil {
		if cerr := q.getMemberStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getMemberStmt: %w", cerr)
		}
	}
	if q.listMembersStmt != nil {
		if cerr := q.listMembersStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listMembersStmt: %w", cerr)
		}
	}
	if q.updateMemberCASStmt != nil {
		if cerr := q.updateMemberCASStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing updateMemberCASStmt: %w", cerr)
		}
	}
	if q.insertTaskStmt != nil {
		if cerr := q.insertTaskStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing insertTaskStmt: %w", cerr)
		}
	}
	if q.getTaskStmt != nil {
		if cerr := q.getTaskStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getTaskStmt: %w", cerr)
		}
	}
	if q.listTasksStmt != nil {
		if cerr := q.listTasksStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listTasksStmt: %w", cerr)
		}
	}
	if q.insertRunStmt != nil {
		if cerr := q.insertRunStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing insertRunStmt: %w", cerr)
		}
	}
	if q.getRunStmt != nil {
		if cerr := q.getRunStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getRunStmt: %w", cerr)
		}
	}
	if q.insertAuditStmt != nil {
		if cerr := q.insertAuditStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing insertAuditStmt: %w", cerr)
		}
	}
	if q.listAuditStmt != nil {
		if cerr := q.listAuditStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listAuditStmt: %w", cerr)
		}
	}
	if q.insertMessageStmt != nil {
		if cerr := q.insertMessageStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing insertMessageStmt: %w", cerr)
		}
	}
	if q.getUnreadMessagesStmt != nil {
		if cerr := q.getUnreadMessagesStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getUnreadMessagesStmt: %w", cerr)
		}
	}
	if q.insertReceiptStmt != nil {
		if cerr := q.insertReceiptStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing insertReceiptStmt: %w", cerr)
		}
	}
	if q.markDeliveredStmt != nil {
		if cerr := q.markDeliveredStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing markDeliveredStmt: %w", cerr)
		}
	}
	if q.markReadStmt != nil {
		if cerr := q.markReadStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing markReadStmt: %w", cerr)
		}
	}
	if q.addDependencyStmt != nil {
		if cerr := q.addDependencyStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing addDependencyStmt: %w", cerr)
		}
	}
	if q.removeDependencyStmt != nil {
		if cerr := q.removeDependencyStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing removeDependencyStmt: %w", cerr)
		}
	}
	if q.getDependenciesStmt != nil {
		if cerr := q.getDependenciesStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getDependenciesStmt: %w", cerr)
		}
	}
	if q.getDependentsStmt != nil {
		if cerr := q.getDependentsStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getDependentsStmt: %w", cerr)
		}
	}
	if q.getTeamDependenciesStmt != nil {
		if cerr := q.getTeamDependenciesStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getTeamDependenciesStmt: %w", cerr)
		}
	}
	return err
}

func (q *Queries) exec(ctx context.Context, stmt *sql.Stmt, query string, args ...interface{}) (sql.Result, error) {
	switch {
	case stmt != nil && q.tx != nil:
		return q.tx.StmtContext(ctx, stmt).ExecContext(ctx, args...)
	case stmt != nil:
		return stmt.ExecContext(ctx, args...)
	default:
		return q.db.ExecContext(ctx, query, args...)
	}
}

func (q *Queries) query(ctx context.Context, stmt *sql.Stmt, query string, args ...interface{}) (*sql.Rows, error) {
	switch {
	case stmt != nil && q.tx != nil:
		return q.tx.StmtContext(ctx, stmt).QueryContext(ctx, args...)
	case stmt != nil:
		return stmt.QueryContext(ctx, args...)
	default:
		return q.db.QueryContext(ctx, query, args...)
	}
}

func (q *Queries) queryRow(ctx context.Context, stmt *sql.Stmt, query string, args ...interface{}) *sql.Row {
	switch {
	case stmt != nil && q.tx != nil:
		return q.tx.StmtContext(ctx, stmt).QueryRowContext(ctx, args...)
	case stmt != nil:
		return stmt.QueryRowContext(ctx, args...)
	default:
		return q.db.QueryRowContext(ctx, query, args...)
	}
}

type Queries struct {
	db                             DBTX
	tx                             *sql.Tx
	createFileStmt                 *sql.Stmt
	createMessageStmt              *sql.Stmt
	createSessionStmt              *sql.Stmt
	deleteFileStmt                 *sql.Stmt
	deleteMessageStmt              *sql.Stmt
	deleteSessionStmt              *sql.Stmt
	deleteSessionFilesStmt         *sql.Stmt
	deleteSessionMessagesStmt      *sql.Stmt
	getAverageResponseTimeStmt     *sql.Stmt
	getFileStmt                    *sql.Stmt
	getFileByPathAndSessionStmt    *sql.Stmt
	getFileReadStmt                *sql.Stmt
	getHourDayHeatmapStmt          *sql.Stmt
	getLastSessionStmt             *sql.Stmt
	getMessageStmt                 *sql.Stmt
	getRecentActivityStmt          *sql.Stmt
	getSessionByIDStmt             *sql.Stmt
	getToolUsageStmt               *sql.Stmt
	getTotalStatsStmt              *sql.Stmt
	getUsageByDayStmt              *sql.Stmt
	getUsageByDayOfWeekStmt        *sql.Stmt
	getUsageByHourStmt             *sql.Stmt
	getUsageByModelStmt            *sql.Stmt
	listAllUserMessagesStmt        *sql.Stmt
	listFilesByPathStmt            *sql.Stmt
	listFilesBySessionStmt         *sql.Stmt
	listLatestSessionFilesStmt     *sql.Stmt
	listMessagesBySessionStmt      *sql.Stmt
	listNewFilesStmt               *sql.Stmt
	listSessionReadFilesStmt       *sql.Stmt
	listSessionsStmt               *sql.Stmt
	listUserMessagesBySessionStmt  *sql.Stmt
	recordFileReadStmt             *sql.Stmt
	renameSessionStmt              *sql.Stmt
	updateMessageStmt              *sql.Stmt
	updateSessionStmt              *sql.Stmt
	updateSessionTitleAndUsageStmt *sql.Stmt
	archiveTeamStmt                *sql.Stmt
	claimNextTaskStmt              *sql.Stmt
	findStaleRunsStmt              *sql.Stmt
	finishRunStmt                  *sql.Stmt
	getTeamStmt                    *sql.Stmt
	insertEventStmt                *sql.Stmt
	insertTeamStmt                 *sql.Stmt
	listEventsAfterStmt            *sql.Stmt
	listTeamsStmt                  *sql.Stmt
	markRunTerminalStmt            *sql.Stmt
	nextEventSeqStmt               *sql.Stmt
	updateRunHeartbeatStmt         *sql.Stmt
	updateTaskCASStmt              *sql.Stmt
	insertMemberStmt               *sql.Stmt
	getMemberStmt                  *sql.Stmt
	listMembersStmt                *sql.Stmt
	updateMemberCASStmt            *sql.Stmt
	insertTaskStmt                 *sql.Stmt
	getTaskStmt                    *sql.Stmt
	listTasksStmt                  *sql.Stmt
	insertRunStmt                  *sql.Stmt
	getRunStmt                     *sql.Stmt
	insertAuditStmt                *sql.Stmt
	listAuditStmt                  *sql.Stmt
	insertMessageStmt              *sql.Stmt
	getUnreadMessagesStmt          *sql.Stmt
	insertReceiptStmt              *sql.Stmt
	markDeliveredStmt              *sql.Stmt
	markReadStmt                   *sql.Stmt
	addDependencyStmt              *sql.Stmt
	removeDependencyStmt           *sql.Stmt
	getDependenciesStmt            *sql.Stmt
	getDependentsStmt              *sql.Stmt
	getTeamDependenciesStmt        *sql.Stmt
}

func (q *Queries) WithTx(tx *sql.Tx) *Queries {
	return &Queries{
		db:                             tx,
		tx:                             tx,
		createFileStmt:                 q.createFileStmt,
		createMessageStmt:              q.createMessageStmt,
		createSessionStmt:              q.createSessionStmt,
		deleteFileStmt:                 q.deleteFileStmt,
		deleteMessageStmt:              q.deleteMessageStmt,
		deleteSessionStmt:              q.deleteSessionStmt,
		deleteSessionFilesStmt:         q.deleteSessionFilesStmt,
		deleteSessionMessagesStmt:      q.deleteSessionMessagesStmt,
		getAverageResponseTimeStmt:     q.getAverageResponseTimeStmt,
		getFileStmt:                    q.getFileStmt,
		getFileByPathAndSessionStmt:    q.getFileByPathAndSessionStmt,
		getFileReadStmt:                q.getFileReadStmt,
		getHourDayHeatmapStmt:          q.getHourDayHeatmapStmt,
		getLastSessionStmt:             q.getLastSessionStmt,
		getMessageStmt:                 q.getMessageStmt,
		getRecentActivityStmt:          q.getRecentActivityStmt,
		getSessionByIDStmt:             q.getSessionByIDStmt,
		getToolUsageStmt:               q.getToolUsageStmt,
		getTotalStatsStmt:              q.getTotalStatsStmt,
		getUsageByDayStmt:              q.getUsageByDayStmt,
		getUsageByDayOfWeekStmt:        q.getUsageByDayOfWeekStmt,
		getUsageByHourStmt:             q.getUsageByHourStmt,
		getUsageByModelStmt:            q.getUsageByModelStmt,
		listAllUserMessagesStmt:        q.listAllUserMessagesStmt,
		listFilesByPathStmt:            q.listFilesByPathStmt,
		listFilesBySessionStmt:         q.listFilesBySessionStmt,
		listLatestSessionFilesStmt:     q.listLatestSessionFilesStmt,
		listMessagesBySessionStmt:      q.listMessagesBySessionStmt,
		listNewFilesStmt:               q.listNewFilesStmt,
		listSessionReadFilesStmt:       q.listSessionReadFilesStmt,
		listSessionsStmt:               q.listSessionsStmt,
		listUserMessagesBySessionStmt:  q.listUserMessagesBySessionStmt,
		recordFileReadStmt:             q.recordFileReadStmt,
		renameSessionStmt:              q.renameSessionStmt,
		updateMessageStmt:              q.updateMessageStmt,
		updateSessionStmt:              q.updateSessionStmt,
		updateSessionTitleAndUsageStmt: q.updateSessionTitleAndUsageStmt,
		archiveTeamStmt:                q.archiveTeamStmt,
		claimNextTaskStmt:              q.claimNextTaskStmt,
		findStaleRunsStmt:              q.findStaleRunsStmt,
		finishRunStmt:                  q.finishRunStmt,
		getTeamStmt:                    q.getTeamStmt,
		insertEventStmt:                q.insertEventStmt,
		insertTeamStmt:                 q.insertTeamStmt,
		listEventsAfterStmt:            q.listEventsAfterStmt,
		listTeamsStmt:                  q.listTeamsStmt,
		markRunTerminalStmt:            q.markRunTerminalStmt,
		nextEventSeqStmt:               q.nextEventSeqStmt,
		updateRunHeartbeatStmt:         q.updateRunHeartbeatStmt,
		updateTaskCASStmt:              q.updateTaskCASStmt,
		insertMemberStmt:               q.insertMemberStmt,
		getMemberStmt:                  q.getMemberStmt,
		listMembersStmt:                q.listMembersStmt,
		updateMemberCASStmt:            q.updateMemberCASStmt,
		insertTaskStmt:                 q.insertTaskStmt,
		getTaskStmt:                    q.getTaskStmt,
		listTasksStmt:                  q.listTasksStmt,
		insertRunStmt:                  q.insertRunStmt,
		getRunStmt:                     q.getRunStmt,
		insertAuditStmt:                q.insertAuditStmt,
		listAuditStmt:                  q.listAuditStmt,
		insertMessageStmt:              q.insertMessageStmt,
		getUnreadMessagesStmt:          q.getUnreadMessagesStmt,
		insertReceiptStmt:              q.insertReceiptStmt,
		markDeliveredStmt:              q.markDeliveredStmt,
		markReadStmt:                   q.markReadStmt,
		addDependencyStmt:              q.addDependencyStmt,
		removeDependencyStmt:           q.removeDependencyStmt,
		getDependenciesStmt:            q.getDependenciesStmt,
		getDependentsStmt:              q.getDependentsStmt,
		getTeamDependenciesStmt:        q.getTeamDependenciesStmt,
	}
}
