// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"
	"database/sql"
)

type Querier interface {
	CreateFile(ctx context.Context, arg CreateFileParams) (File, error)
	CreateMessage(ctx context.Context, arg CreateMessageParams) (Message, error)
	CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error)
	DeleteFile(ctx context.Context, id string) error
	DeleteMessage(ctx context.Context, id string) error
	DeleteSession(ctx context.Context, id string) error
	DeleteSessionFiles(ctx context.Context, sessionID string) error
	DeleteSessionMessages(ctx context.Context, sessionID string) error
	GetAverageResponseTime(ctx context.Context) (int64, error)
	GetFile(ctx context.Context, id string) (File, error)
	GetFileByPathAndSession(ctx context.Context, arg GetFileByPathAndSessionParams) (File, error)
	GetFileRead(ctx context.Context, arg GetFileReadParams) (ReadFile, error)
	GetHourDayHeatmap(ctx context.Context) ([]GetHourDayHeatmapRow, error)
	GetLastSession(ctx context.Context) (Session, error)
	GetMessage(ctx context.Context, id string) (Message, error)
	GetRecentActivity(ctx context.Context) ([]GetRecentActivityRow, error)
	GetSessionByID(ctx context.Context, id string) (Session, error)
	GetToolUsage(ctx context.Context) ([]GetToolUsageRow, error)
	GetTotalStats(ctx context.Context) (GetTotalStatsRow, error)
	GetUsageByDay(ctx context.Context) ([]GetUsageByDayRow, error)
	GetUsageByDayOfWeek(ctx context.Context) ([]GetUsageByDayOfWeekRow, error)
	GetUsageByHour(ctx context.Context) ([]GetUsageByHourRow, error)
	GetUsageByModel(ctx context.Context) ([]GetUsageByModelRow, error)
	ListAllUserMessages(ctx context.Context) ([]Message, error)
	ListFilesByPath(ctx context.Context, path string) ([]File, error)
	ListFilesBySession(ctx context.Context, sessionID string) ([]File, error)
	ListLatestSessionFiles(ctx context.Context, sessionID string) ([]File, error)
	ListMessagesBySession(ctx context.Context, sessionID string) ([]Message, error)
	ListNewFiles(ctx context.Context) ([]File, error)
	ListSessionReadFiles(ctx context.Context, sessionID string) ([]ReadFile, error)
	ListSessions(ctx context.Context) ([]Session, error)
	ListUserMessagesBySession(ctx context.Context, sessionID string) ([]Message, error)
	RecordFileRead(ctx context.Context, arg RecordFileReadParams) error
	RenameSession(ctx context.Context, arg RenameSessionParams) error
	UpdateMessage(ctx context.Context, arg UpdateMessageParams) error
	UpdateSession(ctx context.Context, arg UpdateSessionParams) (Session, error)
	UpdateSessionTitleAndUsage(ctx context.Context, arg UpdateSessionTitleAndUsageParams) error
	ArchiveTeam(ctx context.Context, arg ArchiveTeamParams) error
	ClaimNextTask(ctx context.Context, arg ClaimNextTaskParams) (TeamTask, error)
	FindStaleRuns(ctx context.Context, heartbeatAt sql.NullInt64) ([]TeamRun, error)
	FinishRun(ctx context.Context, arg FinishRunParams) error
	GetTeam(ctx context.Context, id string) (Team, error)
	InsertEvent(ctx context.Context, arg InsertEventParams) error
	InsertTeam(ctx context.Context, arg InsertTeamParams) (Team, error)
	ListEventsAfter(ctx context.Context, arg ListEventsAfterParams) ([]TeamEvent, error)
	ListTeams(ctx context.Context, workspaceID string) ([]Team, error)
	MarkRunTerminal(ctx context.Context, arg MarkRunTerminalParams) error
	NextEventSeq(ctx context.Context, arg NextEventSeqParams) (int64, error)
	UpdateRunHeartbeat(ctx context.Context, arg UpdateRunHeartbeatParams) error
	UpdateTaskCAS(ctx context.Context, arg UpdateTaskCASParams) (TeamTask, error)
	InsertMember(ctx context.Context, arg InsertMemberParams) (TeamMember, error)
	GetMember(ctx context.Context, id string) (TeamMember, error)
	ListMembers(ctx context.Context, teamID string) ([]TeamMember, error)
	UpdateMemberCAS(ctx context.Context, arg UpdateMemberCASParams) (TeamMember, error)
	UpdateMemberSession(ctx context.Context, arg UpdateMemberSessionParams) error
	InsertTask(ctx context.Context, arg InsertTaskParams) (TeamTask, error)
	GetTask(ctx context.Context, arg GetTaskParams) (TeamTask, error)
	ListTasks(ctx context.Context, teamID string) ([]TeamTask, error)
	InsertRun(ctx context.Context, arg InsertRunParams) (TeamRun, error)
	GetRun(ctx context.Context, arg GetRunParams) (TeamRun, error)
	InsertAudit(ctx context.Context, arg InsertAuditParams) error
	ListAudit(ctx context.Context, arg ListAuditParams) ([]TeamAuditEvent, error)
	InsertMessage(ctx context.Context, arg InsertMessageParams) (TeamMailboxMessage, error)
	GetUnreadMessages(ctx context.Context, arg GetUnreadMessagesParams) ([]TeamMailboxMessage, error)
	InsertReceipt(ctx context.Context, arg InsertReceiptParams) error
	MarkDelivered(ctx context.Context, arg MarkDeliveredParams) error
	MarkRead(ctx context.Context, arg MarkReadParams) error
	AddDependency(ctx context.Context, arg AddDependencyParams) error
	RemoveDependency(ctx context.Context, arg RemoveDependencyParams) error
	GetDependencies(ctx context.Context, taskID string) ([]TeamTaskDependency, error)
	GetDependents(ctx context.Context, dependsOnTaskID string) ([]TeamTaskDependency, error)
	GetTeamDependencies(ctx context.Context, teamID string) ([]TeamTaskDependency, error)
	InsertSessionLink(ctx context.Context, arg InsertSessionLinkParams) (TeamSessionLink, error)

	GetSessionLinkByMember(ctx context.Context, arg GetSessionLinkByMemberParams) (TeamSessionLink, error)

	GetSessionLinksByTeam(ctx context.Context, arg GetSessionLinksByTeamParams) ([]TeamSessionLink, error)

}

var _ Querier = (*Queries)(nil)
