// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: team_queries.sql

package db

import (
	"context"
	"database/sql"
)

const archiveTeam = `-- name: ArchiveTeam :exec
UPDATE teams SET status = 'archived', archived_at = ?, updated_at = ? WHERE id = ?
`

type ArchiveTeamParams struct {
	ArchivedAt sql.NullInt64 `json:"archived_at"`
	UpdatedAt  int64         `json:"updated_at"`
	ID         string        `json:"id"`
}

func (q *Queries) ArchiveTeam(ctx context.Context, arg ArchiveTeamParams) error {
	_, err := q.exec(ctx, q.archiveTeamStmt, archiveTeam, arg.ArchivedAt, arg.UpdatedAt, arg.ID)
	return err
}

const claimNextTask = `-- name: ClaimNextTask :one
WITH next AS (
    SELECT id FROM team_tasks
    WHERE team_id = ? AND status = 'queued'
    ORDER BY priority DESC, created_at ASC
    LIMIT 1
)
UPDATE team_tasks
SET assignee_member_id = ?, status = 'assigned', version = version + 1, updated_at = ?
FROM next
WHERE team_tasks.id = next.id AND team_tasks.team_id = ? AND team_tasks.status = 'queued'
RETURNING id, team_id, title, description, status, assignee_member_id, created_by_member_id, priority, version, result_summary, created_at, updated_at, completed_at
`

type ClaimNextTaskParams struct {
	TeamID           string         `json:"team_id"`
	AssigneeMemberID sql.NullString `json:"assignee_member_id"`
	UpdatedAt        int64          `json:"updated_at"`
	TeamID_2         string         `json:"team_id_2"`
}

func (q *Queries) ClaimNextTask(ctx context.Context, arg ClaimNextTaskParams) (TeamTask, error) {
	row := q.queryRow(ctx, q.claimNextTaskStmt, claimNextTask, arg.TeamID, arg.AssigneeMemberID, arg.UpdatedAt, arg.TeamID_2)
	var i TeamTask
	err := row.Scan(
		&i.ID,
		&i.TeamID,
		&i.Title,
		&i.Description,
		&i.Status,
		&i.AssigneeMemberID,
		&i.CreatedByMemberID,
		&i.Priority,
		&i.Version,
		&i.ResultSummary,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CompletedAt,
	)
	return i, err
}

const findStaleRuns = `-- name: FindStaleRuns :many
SELECT id, team_id, member_id, task_id, session_id, status, attempt, heartbeat_at, started_at, finished_at, prompt_tokens, completion_tokens, cost_micros, usage_status, error
FROM team_runs
WHERE status IN ('running', 'waiting_permission', 'queued')
  AND heartbeat_at < ?
`

func (q *Queries) FindStaleRuns(ctx context.Context, heartbeatAt sql.NullInt64) ([]TeamRun, error) {
	rows, err := q.query(ctx, q.findStaleRunsStmt, findStaleRuns, heartbeatAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TeamRun{}
	for rows.Next() {
		var i TeamRun
		if err := rows.Scan(
			&i.ID,
			&i.TeamID,
			&i.MemberID,
			&i.TaskID,
			&i.SessionID,
			&i.Status,
			&i.Attempt,
			&i.HeartbeatAt,
			&i.StartedAt,
			&i.FinishedAt,
			&i.PromptTokens,
			&i.CompletionTokens,
			&i.CostMicros,
			&i.UsageStatus,
			&i.Error,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const finishRun = `-- name: FinishRun :exec
UPDATE team_runs
SET status = 'completed', finished_at = ?, prompt_tokens = ?, completion_tokens = ?, cost_micros = ?, usage_status = 'final'
WHERE id = ? AND team_id = ? AND status = 'running'
`

type FinishRunParams struct {
	FinishedAt       sql.NullInt64 `json:"finished_at"`
	PromptTokens     sql.NullInt64 `json:"prompt_tokens"`
	CompletionTokens sql.NullInt64 `json:"completion_tokens"`
	CostMicros       sql.NullInt64 `json:"cost_micros"`
	ID               string        `json:"id"`
	TeamID           string        `json:"team_id"`
}

func (q *Queries) FinishRun(ctx context.Context, arg FinishRunParams) error {
	_, err := q.exec(ctx, q.finishRunStmt, finishRun,
		arg.FinishedAt,
		arg.PromptTokens,
		arg.CompletionTokens,
		arg.CostMicros,
		arg.ID,
		arg.TeamID,
	)
	return err
}

const getTeam = `-- name: GetTeam :one
SELECT id, workspace_id, leader_session_id, name, description, status, version, max_cost, max_tokens, cost_so_far_micros, created_at, updated_at, archived_at
FROM teams
WHERE id = ? LIMIT 1
`

func (q *Queries) GetTeam(ctx context.Context, id string) (Team, error) {
	row := q.queryRow(ctx, q.getTeamStmt, getTeam, id)
	var i Team
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.LeaderSessionID,
		&i.Name,
		&i.Description,
		&i.Status,
		&i.Version,
		&i.MaxCost,
		&i.MaxTokens,
		&i.CostSoFarMicros,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ArchivedAt,
	)
	return i, err
}

const insertEvent = `-- name: InsertEvent :exec
INSERT INTO team_events (seq, id, workspace_id, team_id, event_type, entity_type, entity_id, actor_member_id, task_id, run_id, message_id, payload_json, published_at, created_at)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type InsertEventParams struct {
	Seq           int64          `json:"seq"`
	ID            string         `json:"id"`
	WorkspaceID   string         `json:"workspace_id"`
	TeamID        string         `json:"team_id"`
	EventType     string         `json:"event_type"`
	EntityType    string         `json:"entity_type"`
	EntityID      string         `json:"entity_id"`
	ActorMemberID sql.NullString `json:"actor_member_id"`
	TaskID        sql.NullString `json:"task_id"`
	RunID         sql.NullString `json:"run_id"`
	MessageID     sql.NullString `json:"message_id"`
	PayloadJSON   sql.NullString `json:"payload_json"`
	PublishedAt   sql.NullInt64  `json:"published_at"`
	CreatedAt     int64          `json:"created_at"`
}

func (q *Queries) InsertEvent(ctx context.Context, arg InsertEventParams) error {
	_, err := q.exec(ctx, q.insertEventStmt, insertEvent,
		arg.Seq,
		arg.ID,
		arg.WorkspaceID,
		arg.TeamID,
		arg.EventType,
		arg.EntityType,
		arg.EntityID,
		arg.ActorMemberID,
		arg.TaskID,
		arg.RunID,
		arg.MessageID,
		arg.PayloadJSON,
		arg.PublishedAt,
		arg.CreatedAt,
	)
	return err
}

const insertTeam = `-- name: InsertTeam :one
INSERT INTO teams (id, workspace_id, leader_session_id, name, description, status, version, max_cost, max_tokens, cost_so_far_micros, created_at, updated_at)
VALUES (?, ?, ?, ?, ?, 'created', 1, ?, ?, 0, ?, ?)
RETURNING id, workspace_id, leader_session_id, name, description, status, version, max_cost, max_tokens, cost_so_far_micros, created_at, updated_at, archived_at
`

type InsertTeamParams struct {
	ID              string         `json:"id"`
	WorkspaceID     string         `json:"workspace_id"`
	LeaderSessionID string         `json:"leader_session_id"`
	Name            string         `json:"name"`
	Description     sql.NullString `json:"description"`
	MaxCost         sql.NullInt64  `json:"max_cost"`
	MaxTokens       sql.NullInt64  `json:"max_tokens"`
	CreatedAt       int64          `json:"created_at"`
	UpdatedAt       int64          `json:"updated_at"`
}

func (q *Queries) InsertTeam(ctx context.Context, arg InsertTeamParams) (Team, error) {
	row := q.queryRow(ctx, q.insertTeamStmt, insertTeam,
		arg.ID,
		arg.WorkspaceID,
		arg.LeaderSessionID,
		arg.Name,
		arg.Description,
		arg.MaxCost,
		arg.MaxTokens,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i Team
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.LeaderSessionID,
		&i.Name,
		&i.Description,
		&i.Status,
		&i.Version,
		&i.MaxCost,
		&i.MaxTokens,
		&i.CostSoFarMicros,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ArchivedAt,
	)
	return i, err
}

const listEventsAfter = `-- name: ListEventsAfter :many
SELECT seq, id, workspace_id, team_id, event_type, entity_type, entity_id, actor_member_id, task_id, run_id, message_id, payload_json, published_at, created_at
FROM team_events
WHERE team_id = ? AND seq > ?
ORDER BY seq ASC
LIMIT ?
`

type ListEventsAfterParams struct {
	TeamID string `json:"team_id"`
	Seq    int64  `json:"seq"`
	Limit  int64  `json:"limit"`
}

func (q *Queries) ListEventsAfter(ctx context.Context, arg ListEventsAfterParams) ([]TeamEvent, error) {
	rows, err := q.query(ctx, q.listEventsAfterStmt, listEventsAfter, arg.TeamID, arg.Seq, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TeamEvent{}
	for rows.Next() {
		var i TeamEvent
		if err := rows.Scan(
			&i.Seq,
			&i.ID,
			&i.WorkspaceID,
			&i.TeamID,
			&i.EventType,
			&i.EntityType,
			&i.EntityID,
			&i.ActorMemberID,
			&i.TaskID,
			&i.RunID,
			&i.MessageID,
			&i.PayloadJSON,
			&i.PublishedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTeams = `-- name: ListTeams :many
SELECT id, workspace_id, leader_session_id, name, description, status, version, max_cost, max_tokens, cost_so_far_micros, created_at, updated_at, archived_at
FROM teams
WHERE workspace_id = ? AND status != 'archived'
ORDER BY created_at DESC
`

func (q *Queries) ListTeams(ctx context.Context, workspaceID string) ([]Team, error) {
	rows, err := q.query(ctx, q.listTeamsStmt, listTeams, workspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Team{}
	for rows.Next() {
		var i Team
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.LeaderSessionID,
			&i.Name,
			&i.Description,
			&i.Status,
			&i.Version,
			&i.MaxCost,
			&i.MaxTokens,
			&i.CostSoFarMicros,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ArchivedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markRunTerminal = `-- name: MarkRunTerminal :exec
UPDATE team_runs
SET status = ?, finished_at = ?, error = ?, usage_status = ?
WHERE id = ? AND team_id = ? AND status = ?
`

type MarkRunTerminalParams struct {
	Status      string         `json:"status"`
	FinishedAt  sql.NullInt64  `json:"finished_at"`
	Error       sql.NullString `json:"error"`
	UsageStatus sql.NullString `json:"usage_status"`
	ID          string         `json:"id"`
	TeamID      string         `json:"team_id"`
	Status_2    string         `json:"status_2"`
}

func (q *Queries) MarkRunTerminal(ctx context.Context, arg MarkRunTerminalParams) error {
	_, err := q.exec(ctx, q.markRunTerminalStmt, markRunTerminal,
		arg.Status,
		arg.FinishedAt,
		arg.Error,
		arg.UsageStatus,
		arg.ID,
		arg.TeamID,
		arg.Status_2,
	)
	return err
}

const nextEventSeq = `-- name: NextEventSeq :one
INSERT INTO team_event_counters(team_id, next_seq, updated_at)
VALUES (?, 2, ?)
ON CONFLICT(team_id) DO UPDATE
SET next_seq = next_seq + 1, updated_at = ?
RETURNING next_seq
`

type NextEventSeqParams struct {
	TeamID      string `json:"team_id"`
	UpdatedAt   int64  `json:"updated_at"`
	UpdatedAt_2 int64  `json:"updated_at_2"`
}

func (q *Queries) NextEventSeq(ctx context.Context, arg NextEventSeqParams) (int64, error) {
	row := q.queryRow(ctx, q.nextEventSeqStmt, nextEventSeq, arg.TeamID, arg.UpdatedAt, arg.UpdatedAt_2)
	var next_seq int64
	err := row.Scan(&next_seq)
	return next_seq, err
}

const updateRunHeartbeat = `-- name: UpdateRunHeartbeat :exec
UPDATE team_runs SET heartbeat_at = ? WHERE id = ?
`

type UpdateRunHeartbeatParams struct {
	HeartbeatAt sql.NullInt64 `json:"heartbeat_at"`
	ID          string        `json:"id"`
}

func (q *Queries) UpdateRunHeartbeat(ctx context.Context, arg UpdateRunHeartbeatParams) error {
	_, err := q.exec(ctx, q.updateRunHeartbeatStmt, updateRunHeartbeat, arg.HeartbeatAt, arg.ID)
	return err
}

const updateTaskCAS = `-- name: UpdateTaskCAS :one
UPDATE team_tasks
SET status = ?, assignee_member_id = ?, result_summary = ?, version = version + 1, updated_at = ?
WHERE id = ? AND team_id = ? AND version = ?
RETURNING id, team_id, title, description, status, assignee_member_id, created_by_member_id, priority, version, result_summary, created_at, updated_at, completed_at
`

type UpdateTaskCASParams struct {
	Status           string         `json:"status"`
	AssigneeMemberID sql.NullString `json:"assignee_member_id"`
	ResultSummary    sql.NullString `json:"result_summary"`
	UpdatedAt        int64          `json:"updated_at"`
	ID               string         `json:"id"`
	TeamID           string         `json:"team_id"`
	Version          int64          `json:"version"`
}

func (q *Queries) UpdateTaskCAS(ctx context.Context, arg UpdateTaskCASParams) (TeamTask, error) {
	row := q.queryRow(ctx, q.updateTaskCASStmt, updateTaskCAS,
		arg.Status,
		arg.AssigneeMemberID,
		arg.ResultSummary,
		arg.UpdatedAt,
		arg.ID,
		arg.TeamID,
		arg.Version,
	)
	var i TeamTask
	err := row.Scan(
		&i.ID,
		&i.TeamID,
		&i.Title,
		&i.Description,
		&i.Status,
		&i.AssigneeMemberID,
		&i.CreatedByMemberID,
		&i.Priority,
		&i.Version,
		&i.ResultSummary,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CompletedAt,
	)
	return i, err
}

const insertMember = `-- name: InsertMember :one
INSERT INTO team_members (id, team_id, session_id, name, role, agent_profile, model_provider, model_name, status, current_task_id, current_run_id, current_tool_name, last_event_seq, max_cost, max_tokens, cost_so_far_micros, version, created_at, updated_at)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, 'created', ?, ?, ?, 0, ?, ?, 0, 1, ?, ?)
RETURNING id, team_id, session_id, name, role, agent_profile, model_provider, model_name, status, current_task_id, current_run_id, current_tool_name, last_event_seq, max_cost, max_tokens, cost_so_far_micros, version, created_at, updated_at, stopped_at
`

type InsertMemberParams struct {
	ID              string         `json:"id"`
	TeamID          string         `json:"team_id"`
	SessionID       sql.NullString `json:"session_id"`
	Name            string         `json:"name"`
	Role            string         `json:"role"`
	AgentProfile    string         `json:"agent_profile"`
	ModelProvider   sql.NullString `json:"model_provider"`
	ModelName       sql.NullString `json:"model_name"`
	CurrentTaskID   sql.NullString `json:"current_task_id"`
	CurrentRunID    sql.NullString `json:"current_run_id"`
	CurrentToolName sql.NullString `json:"current_tool_name"`
	MaxCost         sql.NullInt64  `json:"max_cost"`
	MaxTokens       sql.NullInt64  `json:"max_tokens"`
	CreatedAt       int64          `json:"created_at"`
	UpdatedAt       int64          `json:"updated_at"`
}

func (q *Queries) InsertMember(ctx context.Context, arg InsertMemberParams) (TeamMember, error) {
	row := q.queryRow(ctx, q.insertMemberStmt, insertMember,
		arg.ID, arg.TeamID, arg.SessionID, arg.Name, arg.Role, arg.AgentProfile, arg.ModelProvider, arg.ModelName, arg.CurrentTaskID, arg.CurrentRunID, arg.CurrentToolName, arg.MaxCost, arg.MaxTokens, arg.CreatedAt, arg.UpdatedAt,
	)
	var i TeamMember
	err := row.Scan(
		&i.ID, &i.TeamID, &i.SessionID, &i.Name, &i.Role, &i.AgentProfile, &i.ModelProvider, &i.ModelName, &i.Status, &i.CurrentTaskID, &i.CurrentRunID, &i.CurrentToolName, &i.LastEventSeq, &i.MaxCost, &i.MaxTokens, &i.CostSoFarMicros, &i.Version, &i.CreatedAt, &i.UpdatedAt, &i.StoppedAt,
	)
	return i, err
}

const getMember = `-- name: GetMember :one
SELECT id, team_id, session_id, name, role, agent_profile, model_provider, model_name, status, current_task_id, current_run_id, current_tool_name, last_event_seq, max_cost, max_tokens, cost_so_far_micros, version, created_at, updated_at, stopped_at
FROM team_members
WHERE id = ? LIMIT 1
`

func (q *Queries) GetMember(ctx context.Context, id string) (TeamMember, error) {
	row := q.queryRow(ctx, q.getMemberStmt, getMember, id)
	var i TeamMember
	err := row.Scan(
		&i.ID, &i.TeamID, &i.SessionID, &i.Name, &i.Role, &i.AgentProfile, &i.ModelProvider, &i.ModelName, &i.Status, &i.CurrentTaskID, &i.CurrentRunID, &i.CurrentToolName, &i.LastEventSeq, &i.MaxCost, &i.MaxTokens, &i.CostSoFarMicros, &i.Version, &i.CreatedAt, &i.UpdatedAt, &i.StoppedAt,
	)
	return i, err
}

const listMembers = `-- name: ListMembers :many
SELECT id, team_id, session_id, name, role, agent_profile, model_provider, model_name, status, current_task_id, current_run_id, current_tool_name, last_event_seq, max_cost, max_tokens, cost_so_far_micros, version, created_at, updated_at, stopped_at
FROM team_members
WHERE team_id = ? ORDER BY created_at ASC
`

func (q *Queries) ListMembers(ctx context.Context, teamID string) ([]TeamMember, error) {
	rows, err := q.query(ctx, q.listMembersStmt, listMembers, teamID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TeamMember{}
	for rows.Next() {
		var i TeamMember
		if err := rows.Scan(
			&i.ID, &i.TeamID, &i.SessionID, &i.Name, &i.Role, &i.AgentProfile, &i.ModelProvider, &i.ModelName, &i.Status, &i.CurrentTaskID, &i.CurrentRunID, &i.CurrentToolName, &i.LastEventSeq, &i.MaxCost, &i.MaxTokens, &i.CostSoFarMicros, &i.Version, &i.CreatedAt, &i.UpdatedAt, &i.StoppedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateMemberCAS = `-- name: UpdateMemberCAS :one
UPDATE team_members
SET status = ?, current_task_id = ?, current_run_id = ?, current_tool_name = ?, last_event_seq = ?, version = version + 1, updated_at = ?
WHERE id = ? AND team_id = ? AND version = ?
RETURNING id, team_id, session_id, name, role, agent_profile, model_provider, model_name, status, current_task_id, current_run_id, current_tool_name, last_event_seq, max_cost, max_tokens, cost_so_far_micros, version, created_at, updated_at, stopped_at
`

type UpdateMemberCASParams struct {
	Status          string         `json:"status"`
	CurrentTaskID   sql.NullString `json:"current_task_id"`
	CurrentRunID    sql.NullString `json:"current_run_id"`
	CurrentToolName sql.NullString `json:"current_tool_name"`
	LastEventSeq    int64          `json:"last_event_seq"`
	UpdatedAt       int64          `json:"updated_at"`
	ID              string         `json:"id"`
	TeamID          string         `json:"team_id"`
	Version         int64          `json:"version"`
}

func (q *Queries) UpdateMemberCAS(ctx context.Context, arg UpdateMemberCASParams) (TeamMember, error) {
	row := q.queryRow(ctx, q.updateMemberCASStmt, updateMemberCAS,
		arg.Status, arg.CurrentTaskID, arg.CurrentRunID, arg.CurrentToolName, arg.LastEventSeq, arg.UpdatedAt, arg.ID, arg.TeamID, arg.Version,
	)
	var i TeamMember
	err := row.Scan(
		&i.ID, &i.TeamID, &i.SessionID, &i.Name, &i.Role, &i.AgentProfile, &i.ModelProvider, &i.ModelName, &i.Status, &i.CurrentTaskID, &i.CurrentRunID, &i.CurrentToolName, &i.LastEventSeq, &i.MaxCost, &i.MaxTokens, &i.CostSoFarMicros, &i.Version, &i.CreatedAt, &i.UpdatedAt, &i.StoppedAt,
	)
	return i, err
}

const insertTask = `-- name: InsertTask :one
INSERT INTO team_tasks (id, team_id, title, description, status, assignee_member_id, created_by_member_id, priority, version, created_at, updated_at)
VALUES (?, ?, ?, ?, 'queued', ?, ?, ?, 1, ?, ?)
RETURNING id, team_id, title, description, status, assignee_member_id, created_by_member_id, priority, version, result_summary, created_at, updated_at, completed_at
`

type InsertTaskParams struct {
	ID                string         `json:"id"`
	TeamID            string         `json:"team_id"`
	Title             string         `json:"title"`
	Description       sql.NullString `json:"description"`
	AssigneeMemberID  sql.NullString `json:"assignee_member_id"`
	CreatedByMemberID string         `json:"created_by_member_id"`
	Priority          int64          `json:"priority"`
	CreatedAt         int64          `json:"created_at"`
	UpdatedAt         int64          `json:"updated_at"`
}

func (q *Queries) InsertTask(ctx context.Context, arg InsertTaskParams) (TeamTask, error) {
	row := q.queryRow(ctx, q.insertTaskStmt, insertTask,
		arg.ID, arg.TeamID, arg.Title, arg.Description, arg.AssigneeMemberID, arg.CreatedByMemberID, arg.Priority, arg.CreatedAt, arg.UpdatedAt,
	)
	var i TeamTask
	err := row.Scan(
		&i.ID, &i.TeamID, &i.Title, &i.Description, &i.Status, &i.AssigneeMemberID, &i.CreatedByMemberID, &i.Priority, &i.Version, &i.ResultSummary, &i.CreatedAt, &i.UpdatedAt, &i.CompletedAt,
	)
	return i, err
}

const getTask = `-- name: GetTask :one
SELECT id, team_id, title, description, status, assignee_member_id, created_by_member_id, priority, version, result_summary, created_at, updated_at, completed_at
FROM team_tasks
WHERE id = ? AND team_id = ? LIMIT 1
`

type GetTaskParams struct {
	ID     string `json:"id"`
	TeamID string `json:"team_id"`
}

func (q *Queries) GetTask(ctx context.Context, arg GetTaskParams) (TeamTask, error) {
	row := q.queryRow(ctx, q.getTaskStmt, getTask, arg.ID, arg.TeamID)
	var i TeamTask
	err := row.Scan(
		&i.ID, &i.TeamID, &i.Title, &i.Description, &i.Status, &i.AssigneeMemberID, &i.CreatedByMemberID, &i.Priority, &i.Version, &i.ResultSummary, &i.CreatedAt, &i.UpdatedAt, &i.CompletedAt,
	)
	return i, err
}

const listTasks = `-- name: ListTasks :many
SELECT id, team_id, title, description, status, assignee_member_id, created_by_member_id, priority, version, result_summary, created_at, updated_at, completed_at
FROM team_tasks
WHERE team_id = ? ORDER BY priority DESC, created_at ASC
`

func (q *Queries) ListTasks(ctx context.Context, teamID string) ([]TeamTask, error) {
	rows, err := q.query(ctx, q.listTasksStmt, listTasks, teamID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TeamTask{}
	for rows.Next() {
		var i TeamTask
		if err := rows.Scan(
			&i.ID, &i.TeamID, &i.Title, &i.Description, &i.Status, &i.AssigneeMemberID, &i.CreatedByMemberID, &i.Priority, &i.Version, &i.ResultSummary, &i.CreatedAt, &i.UpdatedAt, &i.CompletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertRun = `-- name: InsertRun :one
INSERT INTO team_runs (id, team_id, member_id, task_id, session_id, status, attempt, heartbeat_at, started_at)
VALUES (?, ?, ?, ?, ?, 'queued', 1, ?, ?)
RETURNING id, team_id, member_id, task_id, session_id, status, attempt, heartbeat_at, started_at, finished_at, prompt_tokens, completion_tokens, cost_micros, usage_status, error
`

type InsertRunParams struct {
	ID          string         `json:"id"`
	TeamID      string         `json:"team_id"`
	MemberID    string         `json:"member_id"`
	TaskID      sql.NullString `json:"task_id"`
	SessionID   string         `json:"session_id"`
	HeartbeatAt sql.NullInt64  `json:"heartbeat_at"`
	StartedAt   sql.NullInt64  `json:"started_at"`
}

func (q *Queries) InsertRun(ctx context.Context, arg InsertRunParams) (TeamRun, error) {
	row := q.queryRow(ctx, q.insertRunStmt, insertRun,
		arg.ID, arg.TeamID, arg.MemberID, arg.TaskID, arg.SessionID, arg.HeartbeatAt, arg.StartedAt,
	)
	var i TeamRun
	err := row.Scan(
		&i.ID, &i.TeamID, &i.MemberID, &i.TaskID, &i.SessionID, &i.Status, &i.Attempt, &i.HeartbeatAt, &i.StartedAt, &i.FinishedAt, &i.PromptTokens, &i.CompletionTokens, &i.CostMicros, &i.UsageStatus, &i.Error,
	)
	return i, err
}

const getRun = `-- name: GetRun :one
SELECT id, team_id, member_id, task_id, session_id, status, attempt, heartbeat_at, started_at, finished_at, prompt_tokens, completion_tokens, cost_micros, usage_status, error
FROM team_runs
WHERE id = ? AND team_id = ? LIMIT 1
`

type GetRunParams struct {
	ID     string `json:"id"`
	TeamID string `json:"team_id"`
}

func (q *Queries) GetRun(ctx context.Context, arg GetRunParams) (TeamRun, error) {
	row := q.queryRow(ctx, q.getRunStmt, getRun, arg.ID, arg.TeamID)
	var i TeamRun
	err := row.Scan(
		&i.ID, &i.TeamID, &i.MemberID, &i.TaskID, &i.SessionID, &i.Status, &i.Attempt, &i.HeartbeatAt, &i.StartedAt, &i.FinishedAt, &i.PromptTokens, &i.CompletionTokens, &i.CostMicros, &i.UsageStatus, &i.Error,
	)
	return i, err
}

const insertAudit = `-- name: InsertAudit :exec
INSERT INTO team_audit_events (id, workspace_id, team_id, member_id, task_id, run_id, session_id, tool_call_id, event_type, action, resource_type, resource_ref, input_hash, summary, decision, scope, created_at)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type InsertAuditParams struct {
	ID           string         `json:"id"`
	WorkspaceID  string         `json:"workspace_id"`
	TeamID       string         `json:"team_id"`
	MemberID     sql.NullString `json:"member_id"`
	TaskID       sql.NullString `json:"task_id"`
	RunID        sql.NullString `json:"run_id"`
	SessionID    sql.NullString `json:"session_id"`
	ToolCallID   sql.NullString `json:"tool_call_id"`
	EventType    string         `json:"event_type"`
	Action       sql.NullString `json:"action"`
	ResourceType sql.NullString `json:"resource_type"`
	ResourceRef  sql.NullString `json:"resource_ref"`
	InputHash    sql.NullString `json:"input_hash"`
	Summary      sql.NullString `json:"summary"`
	Decision     sql.NullString `json:"decision"`
	Scope        sql.NullString `json:"scope"`
	CreatedAt    int64          `json:"created_at"`
}

func (q *Queries) InsertAudit(ctx context.Context, arg InsertAuditParams) error {
	_, err := q.exec(ctx, q.insertAuditStmt, insertAudit,
		arg.ID, arg.WorkspaceID, arg.TeamID, arg.MemberID, arg.TaskID, arg.RunID, arg.SessionID, arg.ToolCallID, arg.EventType, arg.Action, arg.ResourceType, arg.ResourceRef, arg.InputHash, arg.Summary, arg.Decision, arg.Scope, arg.CreatedAt,
	)
	return err
}

const listAudit = `-- name: ListAudit :many
SELECT id, workspace_id, team_id, member_id, task_id, run_id, session_id, tool_call_id, event_type, action, resource_type, resource_ref, input_hash, summary, decision, scope, created_at
FROM team_audit_events
WHERE team_id = ? ORDER BY created_at DESC LIMIT ?
`

type ListAuditParams struct {
	TeamID string `json:"team_id"`
	Limit  int64  `json:"limit"`
}

func (q *Queries) ListAudit(ctx context.Context, arg ListAuditParams) ([]TeamAuditEvent, error) {
	rows, err := q.query(ctx, q.listAuditStmt, listAudit, arg.TeamID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TeamAuditEvent{}
	for rows.Next() {
		var i TeamAuditEvent
		if err := rows.Scan(
			&i.ID, &i.WorkspaceID, &i.TeamID, &i.MemberID, &i.TaskID, &i.RunID, &i.SessionID, &i.ToolCallID, &i.EventType, &i.Action, &i.ResourceType, &i.ResourceRef, &i.InputHash, &i.Summary, &i.Decision, &i.Scope, &i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertMessage = `-- name: InsertMessage :one
INSERT INTO team_mailbox_messages (id, team_id, from_member_id, kind, summary, payload, created_at)
VALUES (?, ?, ?, ?, ?, ?, ?)
RETURNING id, team_id, from_member_id, kind, summary, payload, created_at
`

type InsertMessageParams struct {
	ID           string `json:"id"`
	TeamID       string `json:"team_id"`
	FromMemberID string `json:"from_member_id"`
	Kind         string `json:"kind"`
	Summary      string `json:"summary"`
	Payload      string `json:"payload"`
	CreatedAt    int64  `json:"created_at"`
}

func (q *Queries) InsertMessage(ctx context.Context, arg InsertMessageParams) (TeamMailboxMessage, error) {
	row := q.queryRow(ctx, q.insertMessageStmt, insertMessage,
		arg.ID, arg.TeamID, arg.FromMemberID, arg.Kind, arg.Summary, arg.Payload, arg.CreatedAt,
	)
	var i TeamMailboxMessage
	err := row.Scan(
		&i.ID, &i.TeamID, &i.FromMemberID, &i.Kind, &i.Summary, &i.Payload, &i.CreatedAt,
	)
	return i, err
}

const getUnreadMessages = `-- name: GetUnreadMessages :many
SELECT m.id, m.team_id, m.from_member_id, m.kind, m.summary, m.payload, m.created_at
FROM team_mailbox_messages m
JOIN team_message_receipts r ON r.message_id = m.id
WHERE r.to_member_id = ? AND r.read_at IS NULL
ORDER BY m.created_at ASC
LIMIT ?
`

type GetUnreadMessagesParams struct {
	ToMemberID string `json:"to_member_id"`
	Limit      int64  `json:"limit"`
}

func (q *Queries) GetUnreadMessages(ctx context.Context, arg GetUnreadMessagesParams) ([]TeamMailboxMessage, error) {
	rows, err := q.query(ctx, q.getUnreadMessagesStmt, getUnreadMessages, arg.ToMemberID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TeamMailboxMessage{}
	for rows.Next() {
		var i TeamMailboxMessage
		if err := rows.Scan(
			&i.ID, &i.TeamID, &i.FromMemberID, &i.Kind, &i.Summary, &i.Payload, &i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertReceipt = `-- name: InsertReceipt :exec
INSERT INTO team_message_receipts (id, message_id, to_member_id, delivered_at, read_at)
VALUES (?, ?, ?, ?, ?)
`

type InsertReceiptParams struct {
	ID          string        `json:"id"`
	MessageID   string        `json:"message_id"`
	ToMemberID  string        `json:"to_member_id"`
	DeliveredAt sql.NullInt64 `json:"delivered_at"`
	ReadAt      sql.NullInt64 `json:"read_at"`
}

func (q *Queries) InsertReceipt(ctx context.Context, arg InsertReceiptParams) error {
	_, err := q.exec(ctx, q.insertReceiptStmt, insertReceipt,
		arg.ID, arg.MessageID, arg.ToMemberID, arg.DeliveredAt, arg.ReadAt,
	)
	return err
}

const markDelivered = `-- name: MarkDelivered :exec
UPDATE team_message_receipts
SET delivered_at = ?
WHERE message_id = ? AND to_member_id = ?
`

type MarkDeliveredParams struct {
	DeliveredAt int64  `json:"delivered_at"`
	MessageID   string `json:"message_id"`
	ToMemberID  string `json:"to_member_id"`
}

func (q *Queries) MarkDelivered(ctx context.Context, arg MarkDeliveredParams) error {
	_, err := q.exec(ctx, q.markDeliveredStmt, markDelivered,
		arg.DeliveredAt, arg.MessageID, arg.ToMemberID,
	)
	return err
}

const markRead = `-- name: MarkRead :exec
UPDATE team_message_receipts
SET read_at = ?
WHERE message_id = ? AND to_member_id = ?
`

type MarkReadParams struct {
	ReadAt     int64  `json:"read_at"`
	MessageID  string `json:"message_id"`
	ToMemberID string `json:"to_member_id"`
}

func (q *Queries) MarkRead(ctx context.Context, arg MarkReadParams) error {
	_, err := q.exec(ctx, q.markReadStmt, markRead,
		arg.ReadAt, arg.MessageID, arg.ToMemberID,
	)
	return err
}
