// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: team_queries.sql

package db

import (
	"context"
	"database/sql"
)

const archiveTeam = `-- name: ArchiveTeam :exec
UPDATE teams SET status = 'archived', archived_at = ?, updated_at = ? WHERE id = ?
`

type ArchiveTeamParams struct {
	ArchivedAt sql.NullInt64 `json:"archived_at"`
	UpdatedAt  int64         `json:"updated_at"`
	ID         string        `json:"id"`
}

func (q *Queries) ArchiveTeam(ctx context.Context, arg ArchiveTeamParams) error {
	_, err := q.exec(ctx, q.archiveTeamStmt, archiveTeam, arg.ArchivedAt, arg.UpdatedAt, arg.ID)
	return err
}

const claimNextTask = `-- name: ClaimNextTask :one
WITH next AS (
    SELECT id FROM team_tasks
    WHERE team_id = ? AND status = 'queued'
    ORDER BY priority DESC, created_at ASC
    LIMIT 1
)
UPDATE team_tasks
SET assignee_member_id = ?, status = 'assigned', version = version + 1, updated_at = ?
FROM next
WHERE team_tasks.id = next.id AND team_tasks.team_id = ? AND team_tasks.status = 'queued'
RETURNING id, team_id, title, description, status, assignee_member_id, created_by_member_id, priority, version, result_summary, created_at, updated_at, completed_at
`

type ClaimNextTaskParams struct {
	TeamID           string         `json:"team_id"`
	AssigneeMemberID sql.NullString `json:"assignee_member_id"`
	UpdatedAt        int64          `json:"updated_at"`
	TeamID_2         string         `json:"team_id_2"`
}

func (q *Queries) ClaimNextTask(ctx context.Context, arg ClaimNextTaskParams) (TeamTask, error) {
	row := q.queryRow(ctx, q.claimNextTaskStmt, claimNextTask, arg.TeamID, arg.AssigneeMemberID, arg.UpdatedAt, arg.TeamID_2)
	var i TeamTask
	err := row.Scan(
		&i.ID,
		&i.TeamID,
		&i.Title,
		&i.Description,
		&i.Status,
		&i.AssigneeMemberID,
		&i.CreatedByMemberID,
		&i.Priority,
		&i.Version,
		&i.ResultSummary,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CompletedAt,
	)
	return i, err
}

const findStaleRuns = `-- name: FindStaleRuns :many
SELECT id, team_id, member_id, task_id, session_id, status, attempt, heartbeat_at, started_at, finished_at, prompt_tokens, completion_tokens, cost_micros, usage_status, error
FROM team_runs
WHERE status IN ('running', 'waiting_permission', 'queued')
  AND heartbeat_at < ?
`

func (q *Queries) FindStaleRuns(ctx context.Context, heartbeatAt sql.NullInt64) ([]TeamRun, error) {
	rows, err := q.query(ctx, q.findStaleRunsStmt, findStaleRuns, heartbeatAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TeamRun{}
	for rows.Next() {
		var i TeamRun
		if err := rows.Scan(
			&i.ID,
			&i.TeamID,
			&i.MemberID,
			&i.TaskID,
			&i.SessionID,
			&i.Status,
			&i.Attempt,
			&i.HeartbeatAt,
			&i.StartedAt,
			&i.FinishedAt,
			&i.PromptTokens,
			&i.CompletionTokens,
			&i.CostMicros,
			&i.UsageStatus,
			&i.Error,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const finishRun = `-- name: FinishRun :exec
UPDATE team_runs
SET status = 'completed', finished_at = ?, prompt_tokens = ?, completion_tokens = ?, cost_micros = ?, usage_status = 'final'
WHERE id = ? AND team_id = ? AND status = 'running'
`

type FinishRunParams struct {
	FinishedAt       sql.NullInt64 `json:"finished_at"`
	PromptTokens     sql.NullInt64 `json:"prompt_tokens"`
	CompletionTokens sql.NullInt64 `json:"completion_tokens"`
	CostMicros       sql.NullInt64 `json:"cost_micros"`
	ID               string        `json:"id"`
	TeamID           string        `json:"team_id"`
}

func (q *Queries) FinishRun(ctx context.Context, arg FinishRunParams) error {
	_, err := q.exec(ctx, q.finishRunStmt, finishRun,
		arg.FinishedAt,
		arg.PromptTokens,
		arg.CompletionTokens,
		arg.CostMicros,
		arg.ID,
		arg.TeamID,
	)
	return err
}

const getTeam = `-- name: GetTeam :one
SELECT id, workspace_id, leader_session_id, name, description, status, version, max_cost, max_tokens, cost_so_far_micros, created_at, updated_at, archived_at
FROM teams
WHERE id = ? LIMIT 1
`

func (q *Queries) GetTeam(ctx context.Context, id string) (Team, error) {
	row := q.queryRow(ctx, q.getTeamStmt, getTeam, id)
	var i Team
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.LeaderSessionID,
		&i.Name,
		&i.Description,
		&i.Status,
		&i.Version,
		&i.MaxCost,
		&i.MaxTokens,
		&i.CostSoFarMicros,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ArchivedAt,
	)
	return i, err
}

const insertEvent = `-- name: InsertEvent :exec
INSERT INTO team_events (seq, id, workspace_id, team_id, event_type, entity_type, entity_id, actor_member_id, task_id, run_id, message_id, payload_json, published_at, created_at)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type InsertEventParams struct {
	Seq           int64          `json:"seq"`
	ID            string         `json:"id"`
	WorkspaceID   string         `json:"workspace_id"`
	TeamID        string         `json:"team_id"`
	EventType     string         `json:"event_type"`
	EntityType    string         `json:"entity_type"`
	EntityID      string         `json:"entity_id"`
	ActorMemberID sql.NullString `json:"actor_member_id"`
	TaskID        sql.NullString `json:"task_id"`
	RunID         sql.NullString `json:"run_id"`
	MessageID     sql.NullString `json:"message_id"`
	PayloadJSON   sql.NullString `json:"payload_json"`
	PublishedAt   sql.NullInt64  `json:"published_at"`
	CreatedAt     int64          `json:"created_at"`
}

func (q *Queries) InsertEvent(ctx context.Context, arg InsertEventParams) error {
	_, err := q.exec(ctx, q.insertEventStmt, insertEvent,
		arg.Seq,
		arg.ID,
		arg.WorkspaceID,
		arg.TeamID,
		arg.EventType,
		arg.EntityType,
		arg.EntityID,
		arg.ActorMemberID,
		arg.TaskID,
		arg.RunID,
		arg.MessageID,
		arg.PayloadJSON,
		arg.PublishedAt,
		arg.CreatedAt,
	)
	return err
}

const insertTeam = `-- name: InsertTeam :one
INSERT INTO teams (id, workspace_id, leader_session_id, name, description, status, version, max_cost, max_tokens, cost_so_far_micros, created_at, updated_at)
VALUES (?, ?, ?, ?, ?, 'created', 1, ?, ?, 0, ?, ?)
RETURNING id, workspace_id, leader_session_id, name, description, status, version, max_cost, max_tokens, cost_so_far_micros, created_at, updated_at, archived_at
`

type InsertTeamParams struct {
	ID              string         `json:"id"`
	WorkspaceID     string         `json:"workspace_id"`
	LeaderSessionID string         `json:"leader_session_id"`
	Name            string         `json:"name"`
	Description     sql.NullString `json:"description"`
	MaxCost         sql.NullInt64  `json:"max_cost"`
	MaxTokens       sql.NullInt64  `json:"max_tokens"`
	CreatedAt       int64          `json:"created_at"`
	UpdatedAt       int64          `json:"updated_at"`
}

func (q *Queries) InsertTeam(ctx context.Context, arg InsertTeamParams) (Team, error) {
	row := q.queryRow(ctx, q.insertTeamStmt, insertTeam,
		arg.ID,
		arg.WorkspaceID,
		arg.LeaderSessionID,
		arg.Name,
		arg.Description,
		arg.MaxCost,
		arg.MaxTokens,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i Team
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.LeaderSessionID,
		&i.Name,
		&i.Description,
		&i.Status,
		&i.Version,
		&i.MaxCost,
		&i.MaxTokens,
		&i.CostSoFarMicros,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ArchivedAt,
	)
	return i, err
}

const listEventsAfter = `-- name: ListEventsAfter :many
SELECT seq, id, workspace_id, team_id, event_type, entity_type, entity_id, actor_member_id, task_id, run_id, message_id, payload_json, published_at, created_at
FROM team_events
WHERE team_id = ? AND seq > ?
ORDER BY seq ASC
LIMIT ?
`

type ListEventsAfterParams struct {
	TeamID string `json:"team_id"`
	Seq    int64  `json:"seq"`
	Limit  int64  `json:"limit"`
}

func (q *Queries) ListEventsAfter(ctx context.Context, arg ListEventsAfterParams) ([]TeamEvent, error) {
	rows, err := q.query(ctx, q.listEventsAfterStmt, listEventsAfter, arg.TeamID, arg.Seq, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TeamEvent{}
	for rows.Next() {
		var i TeamEvent
		if err := rows.Scan(
			&i.Seq,
			&i.ID,
			&i.WorkspaceID,
			&i.TeamID,
			&i.EventType,
			&i.EntityType,
			&i.EntityID,
			&i.ActorMemberID,
			&i.TaskID,
			&i.RunID,
			&i.MessageID,
			&i.PayloadJSON,
			&i.PublishedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTeams = `-- name: ListTeams :many
SELECT id, workspace_id, leader_session_id, name, description, status, version, max_cost, max_tokens, cost_so_far_micros, created_at, updated_at, archived_at
FROM teams
WHERE workspace_id = ? AND status != 'archived'
ORDER BY created_at DESC
`

func (q *Queries) ListTeams(ctx context.Context, workspaceID string) ([]Team, error) {
	rows, err := q.query(ctx, q.listTeamsStmt, listTeams, workspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Team{}
	for rows.Next() {
		var i Team
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.LeaderSessionID,
			&i.Name,
			&i.Description,
			&i.Status,
			&i.Version,
			&i.MaxCost,
			&i.MaxTokens,
			&i.CostSoFarMicros,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ArchivedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markRunTerminal = `-- name: MarkRunTerminal :exec
UPDATE team_runs
SET status = ?, finished_at = ?, error = ?, usage_status = ?
WHERE id = ? AND team_id = ? AND status = ?
`

type MarkRunTerminalParams struct {
	Status      string         `json:"status"`
	FinishedAt  sql.NullInt64  `json:"finished_at"`
	Error       sql.NullString `json:"error"`
	UsageStatus sql.NullString `json:"usage_status"`
	ID          string         `json:"id"`
	TeamID      string         `json:"team_id"`
	Status_2    string         `json:"status_2"`
}

func (q *Queries) MarkRunTerminal(ctx context.Context, arg MarkRunTerminalParams) error {
	_, err := q.exec(ctx, q.markRunTerminalStmt, markRunTerminal,
		arg.Status,
		arg.FinishedAt,
		arg.Error,
		arg.UsageStatus,
		arg.ID,
		arg.TeamID,
		arg.Status_2,
	)
	return err
}

const nextEventSeq = `-- name: NextEventSeq :one
INSERT INTO team_event_counters(team_id, next_seq, updated_at)
VALUES (?, 2, ?)
ON CONFLICT(team_id) DO UPDATE
SET next_seq = next_seq + 1, updated_at = ?
RETURNING next_seq
`

type NextEventSeqParams struct {
	TeamID      string `json:"team_id"`
	UpdatedAt   int64  `json:"updated_at"`
	UpdatedAt_2 int64  `json:"updated_at_2"`
}

func (q *Queries) NextEventSeq(ctx context.Context, arg NextEventSeqParams) (int64, error) {
	row := q.queryRow(ctx, q.nextEventSeqStmt, nextEventSeq, arg.TeamID, arg.UpdatedAt, arg.UpdatedAt_2)
	var next_seq int64
	err := row.Scan(&next_seq)
	return next_seq, err
}

const updateRunHeartbeat = `-- name: UpdateRunHeartbeat :exec
UPDATE team_runs SET heartbeat_at = ? WHERE id = ?
`

type UpdateRunHeartbeatParams struct {
	HeartbeatAt sql.NullInt64 `json:"heartbeat_at"`
	ID          string        `json:"id"`
}

func (q *Queries) UpdateRunHeartbeat(ctx context.Context, arg UpdateRunHeartbeatParams) error {
	_, err := q.exec(ctx, q.updateRunHeartbeatStmt, updateRunHeartbeat, arg.HeartbeatAt, arg.ID)
	return err
}

const updateTaskCAS = `-- name: UpdateTaskCAS :one
UPDATE team_tasks
SET status = ?, assignee_member_id = ?, result_summary = ?, version = version + 1, updated_at = ?
WHERE id = ? AND team_id = ? AND version = ?
RETURNING id, team_id, title, description, status, assignee_member_id, created_by_member_id, priority, version, result_summary, created_at, updated_at, completed_at
`

type UpdateTaskCASParams struct {
	Status           string         `json:"status"`
	AssigneeMemberID sql.NullString `json:"assignee_member_id"`
	ResultSummary    sql.NullString `json:"result_summary"`
	UpdatedAt        int64          `json:"updated_at"`
	ID               string         `json:"id"`
	TeamID           string         `json:"team_id"`
	Version          int64          `json:"version"`
}

func (q *Queries) UpdateTaskCAS(ctx context.Context, arg UpdateTaskCASParams) (TeamTask, error) {
	row := q.queryRow(ctx, q.updateTaskCASStmt, updateTaskCAS,
		arg.Status,
		arg.AssigneeMemberID,
		arg.ResultSummary,
		arg.UpdatedAt,
		arg.ID,
		arg.TeamID,
		arg.Version,
	)
	var i TeamTask
	err := row.Scan(
		&i.ID,
		&i.TeamID,
		&i.Title,
		&i.Description,
		&i.Status,
		&i.AssigneeMemberID,
		&i.CreatedByMemberID,
		&i.Priority,
		&i.Version,
		&i.ResultSummary,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CompletedAt,
	)
	return i, err
}
